spring:
  datasource:
    url: jdbc:postgresql://postgres-backend:5432/TASK_TRACKER_DB
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

