spring:
  profiles:
    default: h2

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml

jwt:
  secret: "JWT_SECRET=iV4453VFzU7+RQ6KYqjglpnrvxQ7P2a40S7PPZZ4Qjw="
  expiration: 3600000 # 1 house